project:
  type: website
  output-dir: docs

website:
  title: "High Throughput Sequencing Data"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: 01_Sequencing.qmd
        text: HTS Data
      - href: 02_PublicDatasets.qmd
        text: Sequencing Databases
      - href: 03_QC.qmd
        text: Data QC
      - href: 04_ReferenceGenomes.qmd
        text: Reference Genomes
        
format:
  html:
    theme: cosmo
    css: challengestyles.css
    toc: true
    link-external-newwindow: true
