---
title: "High Throughput Sequencing Data"
format: html
syntax-highlighting: ayu
---

Welcome to our *High Throughput Sequencing Data* course.

During this course you will learn to:

-   Learn about different types of sequencing
-   Explore public databases for sequencing data
-   Download data and quality assess data
-   Explore and download reference genomes

This course is hosted by the Bioinformatics Core at the [DRP-HCB](https://biology.ed.ac.uk/drp).

### Course Setup

If you are using the DRP-HCB Bioinformatics server for this course then all of the data and software is already installed. If you are working through this course from a different Linux computer or server, please make sure the following tools are installed:

::: resources
<h2><i class="fas fa-save"></i> Required software</h2>

- [sra-tools](https://github.com/ncbi/sra-tools)
- [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/)
- [FastQ Screen](https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/)
- [MultiQC](https://github.com/multiqc/multiqc)
- [NanoPlot](https://github.com/wdecoster/nanoplot)

An easy way to install is through [conda](https://continuumio-docs.readthedocs-hosted.com/miniconda/). Check out [our guide](https://drp-hcb-bioinformatics.github.io/DRP-HCB-Bioinformatics/software.html) and explore how to install and work with conda. Tools can then be installed by downloading [the environment (yml) file](https://raw.githubusercontent.com/DRP-HCB-Bioinformatics/High_throughput_sequencing_data/refs/heads/main/env/htsd.yml) and running the following commands to install and activate the environment. 

``` bash
wget https://raw.githubusercontent.com/DRP-HCB-Bioinformatics/High_throughput_sequencing_data/refs/heads/main/env/htsd.yml

conda env create -f htsd.yml

conda activate htsd
``` 
